# users カラム定義変更

# --- !Ups

ALTER TABLE users ALTER COLUMN userid VARCHAR(255);
ALTER TABLE users ALTER COLUMN alias VARCHAR(255);
ALTER TABLE users ALTER COLUMN email VARCHAR(255);
ALTER TABLE users ALTER COLUMN access_token VARCHAR(255);
ALTER TABLE users ALTER COLUMN refresh_token VARCHAR(255);

# --- !Downs

ALTER TABLE users ALTER COLUMN userid VARCHAR(256);
ALTER TABLE users ALTER COLUMN alias VARCHAR(256);
ALTER TABLE users ALTER COLUMN email VARCHAR(256);
ALTER TABLE users ALTER COLUMN access_token VARCHAR(256);
ALTER TABLE users ALTER COLUMN refresh_token VARCHAR(256);
