# users カラム定義変更

# --- !Ups

ALTER TABLE users ALTER COLUMN user_id TYPE VARCHAR(255);
ALTER TABLE users ALTER COLUMN alias TYPE VARCHAR(255);
ALTER TABLE users ALTER COLUMN email TYPE VARCHAR(255);
ALTER TABLE users ALTER COLUMN access_token TYPE VARCHAR(255);
ALTER TABLE users ALTER COLUMN refresh_token TYPE VARCHAR(255);

# --- !Downs

ALTER TABLE users ALTER COLUMN user_id TYPE VARCHAR(256);
ALTER TABLE users ALTER COLUMN alias TYPE VARCHAR(256);
ALTER TABLE users ALTER COLUMN email TYPE VARCHAR(256);
ALTER TABLE users ALTER COLUMN access_token TYPE VARCHAR(256);
ALTER TABLE users ALTER COLUMN refresh_token TYPE VARCHAR(256);
